### PR TITLE
Add Codecov

### PR DESCRIPTION
**Pull request by stevepeak**
Thank you for this awesome list! Let me know if you have questions about Codecov 👍 🌂

### CODE REVIEW

**Comment by stefanbuck** [comment]
Pretty cool extension 👍  This awesome list is not alphabetic sorted. Please add new items at the end. Thank you

**Comment by stevepeak** [comment]
@stefanbuck thank you 😄 I've moved it to the bottom. Cheers!

**Comment by stefanbuck** [comment]
I'm so sorry but since I merged #43 this PR is conflicting

**Comment by stevepeak** [comment]
See #44

**Pull request closed without merging**
