### PR TITLE
add github-plus extension

### PR DESCRIPTION
**Pull request by softvar**
Chrome extension to display size of each file, download link and an option of copying file contents directly to clipboard
https://chrome.google.com/webstore/detail/github-plus/anlikcnbgdeidpacdbdljnabclhahhmd

### CODE REVIEW

**Comment by stefanbuck** [comment]
:+1:

**Comment by stefanbuck** [comment]
Looks like that the screenshots urls are unreachable. Please create a new PR to fix them. Thank you

**Comment by softvar** [comment]
Hey @stefanbuck,

I recently changed the directory structure, my bad.
Have raise a PR for the fix - https://github.com/stefanbuck/awesome-browser-extensions-for-github/pull/50

Please merge it!

**Comment by stefanbuck** [comment]
Thank you

**Pull request merged**
