### PR TITLE
add Module Linker

### PR DESCRIPTION
**Pull request by fiatjaf**

### CODE REVIEW

**Comment by stefanbuck** [comment]
Thanks for submitting your proposal. I've discovered your extension long time ago and to be honest back then I was really sceptical about it. As you probably know I'm the author of OctoLinker which basically aims to solve the same problem. 

I know module linker was created to provide real links unlike OctoLinker which lazy loads file and dependencies on click. Solving this issue is constantly grabbing my attention too. I think I'm close to finish it, but I never had time to make it production ready. However, I wonder if we should join forces so we can work together on creating a better experience without duplicating each others work. 

Apologies, I went a bit off-topic. Great addition for this list.

**Comment by fiatjaf** [comment]
Thank you for adding my humble alternative to your extension.

When I discovered Octolinker I already had a basic version of Module Linker working, then I tried to look at your code to see if an integration was possible, but the architecture was so different that I gave up. Also since you had existed for so much time and had so many users and so on it would basically be impossible for my ideas to get accepted there.

Module Linker does a lot of requests to the GitHub API and other places on page load. That's probably a tradeoff, or maybe there's a way to lazy-load as you do and still get direct links (maybe triggering the load on hover instead of on click?). I actually never thought of lazy-loading or of using an external resolver like you do, and when I saw that you did that I was amazed and even started using external resolvers on Module Linker. I later removed then as I preferred to have an extension that was independent of my services and worked on its own.

Anyway, how are you trying to do it? Lazy-loading on hover? :P

**Comment by stefanbuck** [comment]
Your message makes me smile. I can defiantly see that we both were working on the same thing 😆 Actually I was working on all possible solution at some point in time. The lazy loading on hover approach was really fun to develop.

I calculate the distance between mouse and all link elements to find out which elements is most likely getting clicked next, to speed this up even more. However, it doesn't solve the issue of having a real anchor tag which is the actual goal, besides making OctoLinker faster. 

For all external links I perform a batch request against our [live resolver service](https://github.com/OctoLinker/live-resolver) which does all the lookup calls to registry.npmjs.org and others for me. This works really well. 

Resolving relative files is slightly more complicated. As you pointed out OctoLinker is lazy loading relative files which means it process a list of possible locations until one of them returns status code 200. This works fine in the current version, but in order to get real anchor tags this needs to be done on page load.

As you can imagine, this is really brutal and would hit GitHub thousand times a day for a single user even this doesn't click any link, just by browsing code on Github.com. 

Then I was considering to only preload link in the visible viewport, but that's also slightly tricky and could easily cause other issues. 

For a long time I was considering to have anchor tags for external links only and still lazy load relative files. Although I wasn't really happy with this, because UX wise it's really confusing. 

This leads to the last option, which is using the GitHub API like you do. This works really nice and seems to be the best option (developer wise). I'm just concerned that setting up a token will scare users and higher the entry barrier for new users. 

Did you received any feedback from users about that?

**Comment by fiatjaf** [comment]
None, but meh, I don't have many users.

I guess most of my users are power-users who aren't easily scared, or maybe that's the reason I don't have many :P

Anyway, Module Linker kinda works without a GitHub token, it just stops working for the relative links after some time if the user is browsing a lot of code.

--breaking news--

For the previous paragraphs I was under the impression that Module Linker was doing tons of calls, but I just went to see my own code and actually it does just one call, to `repos/${user}/${repo}/git/trees/${sha}?recursive=4`, and that (hopefully) returns all file in the repository. Also, that is cached so if the user browses many pages in the same repository and the page isn't fully reloaded it doesn't have to do more than one request.

--back to normality--

I didn't know you had already implemented lazy-loading on hover, much less this super sophisticated stuff that calculates distances. I mentioned it here as if it was a new idea. Let's get back to it: why can't the lazy load turn the link into a direct anchor when it finishes?

**Comment by stefanbuck** [comment]
You're right, the API supports 60 requests per hour for unauthenticated users https://developer.github.com/v3/#rate-limiting. Also as you mentioned, this response is cached by the browser so maybe nothing to fear about. Maybe I should just try it out and see what happens and if people will complain about it. 

Lazy-loading on hover was just a feature branch which was never merged. Technically it's possible to inject an anchor when the lazy loading has fished, but UX wise it wasn't that great. A regular user expect to see the target url when hovering over a link. Also he want's to use CMD + click to open this url in a new tab. All this isn't possible because it was way to slow to lazy-load the target url. 

Anyway, I feel much more confident with pushing the API request further now.

**Pull request merged**
