### PR TITLE
Add MiniGitHub

### PR DESCRIPTION
**Pull request by mbad0la**
Hey Stefan!

Hope you find my add-on a good addition to your awesome-list :)

### CODE REVIEW

**Comment by stefanbuck** [comment]
Sure, but could you please pick two images to keep the list consistent. Thank you

**Comment by stefanbuck** [comment]
Also needs a rebase after merging #46

**Comment by mbad0la** [comment]
@stefanbuck , I replaced the screenshots with a gif. Hope that works.

**Comment by stefanbuck** [comment]
Perfect 👍  Thank you

**Pull request merged**
