### PR TITLE
add github-omnibar

### PR DESCRIPTION
**Pull request by jcouyang**

### CODE REVIEW

**Comment by stefanbuck** [comment]
Looks good! Just one thing, can you upload the preview image somewhere else e.g. [github file upload](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) please? Evernote does a redirect which let the CI failing. Thank you

**Comment by laughedelic** [comment]
I think there is some copy-paste mistake: the chrome icon link refers to some daydream plugin. Here is the correct one:
- `https://chrome.google.com/webstore/detail/github-omnibar/njccjmmakcbdpnlbodllfgiloenfpocb`

**Comment by stefanbuck** [comment]
Good catch @laughedelic :+1:

**Comment by jcouyang** [comment]
jcouyang__jichao_ouyang_

really nice pickup thanks

**Pull request merged**
